DesingPattermsAsp/Models/ErrorViewModel.cs
using System;

namespace DesingPattermsAsp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesingPattermsAsp/Models/ViewModels/BeerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesingPattermsAsp.Models.ViewModels
{
    public class BeerViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
    }
}

DesingPattermsAsp/Models/ViewModels/FormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesingPattermsAsp.Models.ViewModels
{
    public class FormViewModel
    {
        [Required]
        [Display(Name = "Nombre")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Estilo")]
        public string Style { get; set; }
        [Display(Name = "Marca")]
        public Guid? BrandId { get; set; }
        [Display(Name = "Otra Marca")]
        public string OtherBrand { get; set; }
    }
}

DesingPattermsAsp/Controllers/BeerController.cs
using DesignPatterns.Models.Data;
using DesignPatterns.Repository;
using DesingPattermsAsp.Models.ViewModels;
using DesingPattermsAsp.Strategy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesingPattermsAsp.Controllers
{
    public class BeerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BeerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<BeerViewModel> beers = from d in _unitOfWork.Beers.Get()
                                               select new BeerViewModel
                                               {
                                                   Id = d.BeerId,
                                                   Name = d.Name,
                                                   Style = d.Style
                                               };
            return View("Index", beers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            GetBrandsData();
            return View();
        }

        [HttpPost]
        public IActionResult Add(FormViewModel formView)
        {
            if (!ModelState.IsValid)
            {
                GetBrandsData();
                return View("Add", formView);
            }

            var context = formView.BrandId == null 
                ? new BeerContext(new BeerWithBrandStrategy()) 
                : new BeerContext(new BeerStrategy());

            context.Add(formView, _unitOfWork);
            return RedirectToAction("Index");
        }

        #region HELPERS
        private void GetBrandsData()
        {
            var brands = _unitOfWork.Brands.Get();
            ViewBag.Brands = new SelectList(brands, "BrandId", "Name");
        }
        #endregion
    }
}

DesingPattermsAsp/Controllers/GeneratorFileController.cs
using DesignPatterns.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tools.Generator;

namespace DesingPattermsAsp.Controllers
{
    public class GeneratorFileController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private GeneratorConcreteBuilder _generatorConcreteBuilder;
        public GeneratorFileController(IUnitOfWork unitOfWork, GeneratorConcreteBuilder generatorConcreteBuilder = null)
        {
            _unitOfWork = unitOfWork;
            _generatorConcreteBuilder = generatorConcreteBuilder;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateFile(int optionFile)
        {
            try
            {
                var beer = _unitOfWork.Beers.Get();
                List<string> content = beer.Select(d => d.Name).ToList();
                string paht = "file" + DateTime.Now.Ticks + new Random().Next(1000) + ".txt";
                var generatorDirector = new GeneratorDirector_(_generatorConcreteBuilder);
                if (optionFile == 1)
                {
                    generatorDirector.CreateSimpleJsonGenerator(content, paht);
                }
                else
                {
                    generatorDirector.CreateSimplePipeGenerator(content, paht);
                }
                var generator = _generatorConcreteBuilder.GetGenerator();
                generator.Save();
                return Json("Archivo generado");
            }
            catch (Exception ex)
            {
                return BadRequest();
            }
        }
    }
}

DesingPattermsAsp/Controllers/HomeController.cs
using DesignPatterns.Models.Data;
using DesignPatterns.Repository;
using DesingPattermsAsp.Configuration;
using DesingPattermsAsp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tools;

namespace DesingPattermsAsp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IOptions<MyConfig> _config;

        private readonly IRepository<Beer> _repository;

        public HomeController(IOptions<MyConfig> config, IRepository<Beer> repository)
        {
            _config = config;
            _repository = repository;
        }

        public IActionResult Index()
        {
            Log.GetInstance(_config.Value.PathLog).Save("Entro a Index");

            IEnumerable<Beer> lst = _repository.Get();

            return View("Index", lst);
        }

        public IActionResult Privacy()
        {
            Log.GetInstance(_config.Value.PathLog).Save("Entro a Privacy");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesingPattermsAsp/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tools.Earn;

namespace DesingPattermsAsp.Controllers
{
    public class ProductDetailController : Controller
    {
        private EarnFactory _localEarnFactory;

        public ProductDetailController(LocalEarnFactory localEarnFactory)
        {
            _localEarnFactory = localEarnFactory;
        }

        public IActionResult Index(decimal total)
        {
            //factories
            //LocalEarnFactory localEarnFactory = new LocalEarnFactory(0.20m);  Ya no es necesario tener la resposabilidad, ya que con Inyeccion de Dependencia lo hace
            ForeignEarnFactory foreignEarnFactory = new ForeignEarnFactory(0.30m, 20m);

            //products
            var localEarn = _localEarnFactory.GetEarn();
            var foreignEarn = foreignEarnFactory.GetEarn();

            //Total
            ViewBag.totalLocal = total + localEarn.Earn(total);
            ViewBag.totalForeign = total + foreignEarn.Earn(total);

            return View();
        }
    }
}

DesingPattermsAsp/Views/Beer/Add.cshtml
@model DesingPattermsAsp.Models.ViewModels.FormViewModel

<form asp-controller="Beer" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Style"></label>
        <input class="form-control" asp-for="Style" />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BrandId"></label>
        <select class="form-control" asp-for="BrandId" asp-items="@ViewBag.Brands"></select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="OtherBrand"></label>
        <input class="form-control" asp-for="OtherBrand" />
        <span asp-validation-for="OtherBrand" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
    </div>

</form>

DesingPattermsAsp/Views/Beer/Index.cshtml
@model IEnumerable<DesingPattermsAsp.Models.ViewModels.BeerViewModel>
<div class="row">
    <div class="col-12">
        <a class="btn btn-primary" href="~/Beer/Add">Nueva Cerveza</a>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <table class="table">
            <tr>
                <th>Nombre</th>
            </tr>
        </table>
        @foreach (var beer in Model)
        {
            <tr>@beer.Name</tr>
        }
    </div>
</div>

DesingPattermsAsp/Views/GeneratorFile/Index.cshtml
<div class="row">
    <div class="col-8" offset-2>
        <div class="form-group">
            <select id="optionFile" class="form-control">
                <option value="1">Json</option>
                <option value="2">Pipe</option>
            </select>
        </div>
        <div class="form-group">
            <button class="btn btn-success" onclick="generate();">Generar</button>
        </div>
    </div>
</div>
<script>
    function generate() {
        let optionFile = document.getElementById("optionFile").value;
        fetch("@Url.Content("~/GeneratorFile/CreateFile")" + "?optionFile=" + optionFile)
            .then(res => res.json())
            .then(json => alert(json))
    }
</script>

DesingPattermsAsp/Views/Home/Index.cshtml
@using DesignPatterns.Models.Data
@model IEnumerable<Beer>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-12">
        @foreach (var beer in Model)
        {
            <p>@beer.Name</p>
        }
    </div>
</div>

DesingPattermsAsp/Views/ProductDetail/Index.cshtml
@{ 
    decimal totalLocal = (decimal)ViewBag.totalLocal;
    decimal totalForeign = (decimal)ViewBag.totalForeign;
}

<div class="row">
    <div class="col-12">
        <label>Total local</label>
        <b>@totalLocal</b>
        <label>Total extrangero</label>
        <b>@totalForeign</b>
    </div>
</div>

DesingPattermsAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesingPattermsAsp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesingPattermsAsp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DesingPattermsAsp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>